In [2]:
import gensim
from gensim.models import word2vec, KeyedVectors

In [3]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [4]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [5]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [6]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [7]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [13]:
wv.similarity('cricket','game')

np.float32(0.21875007)

In [10]:
vec=wv['man']-wv['woman']+wv['king']

In [11]:
vec

array([ 2.08984375e-01,  2.37792969e-01,  1.46301270e-01,  1.64062500e-01,
       -5.39550781e-02,  3.00292969e-02,  2.78320312e-02, -2.16979980e-01,
        8.30078125e-02,  3.16642761e-01, -1.16210938e-01, -2.08984375e-01,
       -1.98730469e-01, -5.12695312e-02, -2.42919922e-01, -2.23388672e-01,
        1.24511719e-01,  1.18011475e-01,  1.36718750e-02,  5.88378906e-02,
        3.49121094e-02,  1.62185669e-01,  1.40869141e-01,  2.73437500e-01,
        1.54907227e-01, -1.35742188e-01, -1.59179688e-01,  5.59082031e-02,
        3.67187500e-01,  1.35375977e-01,  1.23046875e-01,  2.04711914e-01,
        2.86132812e-01,  4.85229492e-01, -3.02734375e-01,  2.14843750e-01,
       -1.95312500e-02, -7.22656250e-02,  2.37792969e-01,  2.93945312e-01,
        3.27392578e-01, -2.41943359e-01,  3.36914062e-01,  1.58752441e-01,
        4.34570312e-01, -6.88476562e-02, -1.09863281e-01,  8.30078125e-03,
       -7.58056641e-02, -9.89379883e-02, -3.48388672e-01,  2.81593323e-01,
       -2.59521484e-01, -

In [14]:
wv.most_similar([vec])

[('king', 0.874125063419342),
 ('kings', 0.6618716716766357),
 ('crown_prince', 0.48997625708580017),
 ('clown_prince', 0.48778095841407776),
 ('prince', 0.486490935087204),
 ('King', 0.47865110635757446),
 ('ruler', 0.4751032292842865),
 ('sultan', 0.47439607977867126),
 ('undisputed_king', 0.4717574119567871),
 ('princes', 0.4686875641345978)]

In [15]:
wv.most_similar('vinay')

[('ami_tomar', 0.7279219031333923),
 ('accha', 0.7185806035995483),
 ('aapne', 0.7165566682815552),
 ('mein_bahut', 0.7099365592002869),
 ('rakh', 0.7097412943840027),
 ('kitna', 0.7086414694786072),
 ('mein_kya', 0.7045689821243286),
 ('tumne', 0.6981911063194275),
 ('tumhare', 0.695633053779602),
 ('hai_na', 0.6947668790817261)]